// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHsG6XFKyFgZSWsRlei2S-97a5t5x-2IM',
    appId: '1:639207536443:web:7e1ad632703f651d8ce91e',
    messagingSenderId: '639207536443',
    projectId: 'fir-course-52b1e',
    authDomain: 'fir-course-52b1e.firebaseapp.com',
    storageBucket: 'fir-course-52b1e.firebasestorage.app',
    measurementId: 'G-EHJBV25P6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULfM7Hdbn6LbRPchKf2ZYPcAhmZXvoMQ',
    appId: '1:639207536443:android:21dabde300158d968ce91e',
    messagingSenderId: '639207536443',
    projectId: 'fir-course-52b1e',
    storageBucket: 'fir-course-52b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFsRr0Wl7Pdl81sNFl3RYsuw78ZawJHY',
    appId: '1:639207536443:ios:a4858a41c2f447cc8ce91e',
    messagingSenderId: '639207536443',
    projectId: 'fir-course-52b1e',
    storageBucket: 'fir-course-52b1e.firebasestorage.app',
    iosBundleId: 'com.example.idkfirbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTFsRr0Wl7Pdl81sNFl3RYsuw78ZawJHY',
    appId: '1:639207536443:ios:a4858a41c2f447cc8ce91e',
    messagingSenderId: '639207536443',
    projectId: 'fir-course-52b1e',
    storageBucket: 'fir-course-52b1e.firebasestorage.app',
    iosBundleId: 'com.example.idkfirbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHsG6XFKyFgZSWsRlei2S-97a5t5x-2IM',
    appId: '1:639207536443:web:2950fc0a2b21a0b88ce91e',
    messagingSenderId: '639207536443',
    projectId: 'fir-course-52b1e',
    authDomain: 'fir-course-52b1e.firebaseapp.com',
    storageBucket: 'fir-course-52b1e.firebasestorage.app',
    measurementId: 'G-EKJZ764ELZ',
  );
}
